version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mendoshop_db_docker
    # Forzamos compatibilidad de contrase√±as para MySQL 8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mendoshop
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pToor"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: mendoshop_app_docker
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mendoshop?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor

volumes:
  mysql_data: